version: 2

project_name: dhcp-adguard-sync

before:
  hooks:
    - go mod tidy

builds:
  - id: standard
    env:
      - CGO_ENABLED=0
    goos: [freebsd, linux]
    goarch: [amd64, arm64, arm]
    goarm: ["6", "7"]
    flags: ["-trimpath"]
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: standard
    builds: [standard]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}_
      {{- .Version }}
    format: tar.gz
    files:
      - README*
      - LICENSE*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

snapshot:
  version_template: "{{ incpatch .Version }}-next"