version: 2

project_name: dhcpsync

before:
  hooks:
    - go mod tidy

builds:
  - id: standard
    env:
      - CGO_ENABLED=0
#    goos: [freebsd, linux]
    goos: [freebsd]
    goarch: [amd64] # OPNSense nto supported elsewhere i think
#    goarch: [amd64, arm64, arm]
#    goarm: ["6", "7"]
    flags: ["-trimpath"]
    ldflags:
      - -s -w
      - -X dhcpsync/cmd.version={{.Version}}
      - -X dhcpsync/cmd.commit={{.Commit}}
      - -X dhcpsync/cmd.date={{.Date}}

archives:
  - id: standard
    name_template: '{{ .ProjectName }}_{{- .Os }}_{{- .Arch }}{{- if .Arm }}v{{ .Arm }}{{ end }}_{{- "v" }}{{- .Version }}'
    files:
      - README*
      - LICENSE*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

snapshot:
  version_template: "{{ incpatch .Version }}-next"
