version: 2

project_name: dhcp-adguard-sync

before:
  hooks:
    - go mod tidy

builds:
  - id: opnsense
    env:
      - CGO_ENABLED=0
    goos:
      - freebsd
    goarch:
      - amd64
    binary: dhcp-adguard-sync
    dir: cmd/dhcp-adguard-sync
    flags: ["-trimpath"]
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    output: opnsense-plugin/src/usr/local/sbin/{{ .ProjectName }}

  - id: standard
    env:
      - CGO_ENABLED=0
    goos: [freebsd, linux]
    goarch: [amd64, arm64, arm]
    goarm: ["6", "7"]
    flags: ["-trimpath"]
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    ignore:
      - goos: freebsd
        goarch: amd64

archives:
  - id: opnsense
    builds: [opnsense]
    name_template: '{{ .ProjectName }}_opnsense_{{ .Version }}'
    format: tar.gz
    files:
      - src: 'opnsense-plugin/**/*'
      - src: 'README*'
      - src: 'LICENSE*'
    rlcp: true

  - id: standard
    builds: [standard]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end }}
    format: tar.gz
    files:
      - src: 'README*'
      - src: 'LICENSE*'
    rlcp: true

nfpms:
  - id: standard
    builds: [standard]
    vendor: Your Name
    homepage: https://github.com/yourusername/dhcp-adguard-sync
    maintainer: Your Name <your.email@example.com>
    description: |
      Sync DHCP leases to AdGuard Home
    license: MIT
    formats: [deb, freebsd]
    contents:
      - src: ./scripts/dhcp-adguard-sync.service
        dst: /etc/systemd/system/dhcp-adguard-sync.service
        type: config
        file_info:
          mode: 0644
    scripts:
      postinstall: ./scripts/postinstall.sh
      preremove: ./scripts/preremove.sh
    release: 1
    section: net
    priority: optional

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

signs:
  - cmd: cosign
    artifacts: checksum
    args:
      - sign-blob
      - --key=env://COSIGN_PRIVATE_KEY
      - --output=${signature}
      - ${artifact}
    env:
      - COSIGN_PASSWORD

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

snapshot:
  name_template: "{{ incpatch .Version }}-next"