default_install_hook_types: [pre-commit, prepare-commit-msg, commit-msg]

repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # Format commit messages
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]  # Change to commit-msg

  # - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  #   rev: v9.22.0
  #   hooks:
  #     - id: commitlint
  #       stages: [commit-msg]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^cmd/templates/config\.yaml$
      - id: check-added-large-files

  - repo: local
    hooks:
      # Go Code Formatting
      - id: goimports
        name: goimports
        entry: bash -c 'go install golang.org/x/tools/cmd/goimports@latest && goimports'
        language: system
        types: [ go ]
        pass_filenames: false
        args: [ '-w' ]

      - id: gofumpt
        name: gofumpt
        entry: bash -c 'go install mvdan.cc/gofumpt@latest && gofumpt'
        language: system
        types: [go]
        args: ['-w', '-l']

      - id: golines
        name: golines
        entry: bash -c 'go install github.com/segmentio/golines@latest && golines'
        language: system
        types: [ go ]
        args: [ '-w' ]
