# Configuration for dhcp-adguard-sync

# AdGuard Home credentials
ADGUARD_USERNAME=admin
ADGUARD_PASSWORD=changeme
  
  # AdGuard Home connection settings
ADGUARD_URL=127.0.0.1:3000
ADGUARD_SCHEME=http
  
  # DHCP lease file location
DHCP_LEASE_PATH=/var/dhcpd/var/db/dhcpd.leases

# Optional settings
#PRESERVE_DELETED_HOSTS=true
#DEBUG=true
#DRY_RUN=false
#ADGUARD_TIMEOUT=10

# Logging configuration
#LOG_LEVEL=info
#LOG_FILE=/var/log/dhcp-adguard-sync/sync.log
#MAX_LOG_SIZE=100
#MAX_BACKUPS=3
#MAX_AGE=28
