name: Build OPNsense Plugin Package

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: build --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create repository structure
        run: |
          # Create repository directory structure
          mkdir -p repo/FreeBSD:13:amd64/Latest
          mkdir -p repo/packages

          # Create a simple package manifest
          cat > repo/packages/os-dhcpadguardsync.ucl << EOF
          name: "os-dhcpadguardsync"
          origin: "opnsense/os-dhcpadguardsync"
          version: "${GITHUB_REF_NAME#v}"
          comment: "DHCP AdGuard Sync Plugin for OPNsense"
          maintainer: "jeeftor@gmail.com"
          www: "https://github.com/${{ github.repository }}"
          prefix: "/usr/local"
          desc: "Synchronizes DHCP leases with AdGuard Home clients"
          EOF

          # Copy plugin files to repository
          mkdir -p repo/packages/os-dhcpadguardsync
          cp -r opnsense-plugin/* repo/packages/os-dhcpadguardsync/

          # Copy the built binary to the plugin's files directory
          mkdir -p repo/packages/os-dhcpadguardsync/src/opnsense/scripts
          cp dist/opnsense-lease-sync_freebsd_amd64_v1/opnsense-lease-sync repo/packages/os-dhcpadguardsync/src/opnsense/scripts/
          chmod +x repo/packages/os-dhcpadguardsync/src/opnsense/scripts/opnsense-lease-sync

          # Create a dummy package file
          touch repo/FreeBSD:13:amd64/Latest/os-dhcpadguardsync-${GITHUB_REF_NAME#v}.txz

      - name: Create repository configuration file
        run: |
          cat > repo/dhcpadguardsync.conf << EOF
          dhcpadguardsync: {
            url: "https://raw.githubusercontent.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/repo-packages/packages",
            enabled: yes,
            priority: 50
          }
          EOF

      - name: Create installation instructions
        run: |
          cat > repo/README.md << EOF
          # DHCP AdGuard Sync Plugin Repository

          To install this plugin on your OPNsense firewall:

          1. SSH into your OPNsense system
          2. Run the following command:

          \`\`\`bash
          fetch -o /usr/local/etc/pkg/repos/dhcpadguardsync.conf https://raw.githubusercontent.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/repo-packages/dhcpadguardsync.conf
          \`\`\`

          3. Update the package cache:

          \`\`\`bash
          pkg update
          \`\`\`

          4. Install the plugin:

          \`\`\`bash
          pkg install os-dhcpadguardsync
          \`\`\`

          Alternatively, you can install through the OPNsense web interface:
          1. Navigate to System > Firmware > Plugins
          2. Click "Check for updates"
          3. Find "os-dhcpadguardsync" in the list and click "Install"
          EOF

      - name: Deploy to repo-packages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: repo-packages
          folder: repo
          clean: false
