name: Release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create OPNsense plugin package (simple approach)
      - name: Create OPNsense plugin package
        run: |
          cd opnsense-plugin
          tar -czf ../os-dhcpadguardsync-plugin.tar.gz .

      - name: Upload OPNsense plugin to release
        uses: softprops/action-gh-release@v1
        with:
          files: os-dhcpadguardsync-plugin.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
