name: Release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Build OPNsense plugin package
      - name: Set up FreeBSD environment
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          prepare: |
            pkg install -y gmake
            mkdir -p /usr/ports/Mk
            fetch -o /usr/ports/Mk/plugins.mk https://raw.githubusercontent.com/opnsense/plugins/master/Mk/plugins.mk

      - name: Build OPNsense plugin
        run: |
          cd opnsense-plugin
          gmake package
          mv work/pkg/*.txz ../os-dhcpadguardsync.txz

      - name: Upload OPNsense plugin to release
        uses: softprops/action-gh-release@v1
        with:
          files: os-dhcpadguardsync.txz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
